name: tests

on:
    push

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Check files
              run: |
                  dir

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install black coverage flake8 flit mccabe mypy pylint pytest tox tox-gh-actions pillow requests

            - name: Run tox
              run: |
                  python -m tox -e py39
                  dir

            - name: Generate PyLint Badge
              run: |
                  python scripts/generate_pylint_badge.py

            - name: Upload raw coverage as artifact
              uses: actions/upload-artifact@v2
              with:
                name: .coverage
                path: .coverage
                retention-days: 5

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  fail_ci_if_error: true
                  functionalities:
                    coveragepy
