name: publish

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Check files
              run: |
                dir

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install black coverage flake8 flit mccabe mypy pylint pytest tox tox-gh-actions pillow

            - name: Publish to PyPI
              env:
                  FLIT_USERNAME: __token__
                  FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
              run: |
                  flit publish
